### ISSUE TITLE
rocon uri check fails on turtlebot2

### ISSUE THREAD

**Issue by jihoonl** [robotics-in-concert/rocon_tools#17]
rocon_uri is failing to parse the following uri format.

`rocon:/kobuki|turtlebot2`

It gives hardware_platform specification is invalid [kobuki|turtlebot2] error.

**Comment by stonier** [comment]
It's a simpler problem than this

```
rocon:/turtlebot2
```

also fails with `hardware_platform specification is invalid [turtlebot2]`. Anything but `turtlebot2` is ok.

**Comment by stonier** [comment]
I imagined a substring problem, but this code also fails:

```
    foo_rules = [
             'option verbose',
             'pattern           ::= r"foo3" | r"foo2"',
              ]
    input_string = "foo2"
    result = rule_parser.match(foo_rules, input_string)
```

with:

```
Parsing rule: "pattern" for string:"foo2"
.Parsing regular:"foo3" for string:"foo2"
.Parsed regular :"foo3" - value=""
.Parsing regular:"foo2" for string:"foo2"
.Parsed regular :"foo2" - value=""
Parsed rule :"pattern" - value=""
foo2
^
Result None
```

**Comment by jihoonl** [comment]
Is  integer matter in parsing?

**Comment by stonier** [comment]
In summary - was a problem induced by the partial matching of a terminal symbol in ebnf language against the input value. e.g. `turtlebot` was matching against `turtlebot2` input. Rather than making an elaborate fix in the ebnf parser (there might be some very good reason why it is like that of which I am unaware), I opted for creating the terminal symbols in the ebnf rules in reverse alphabetical order.

I'll email the guy and ask him about this, but for now, it works in rocon.
