### ISSUE TITLE
Delay of find_service function when running remote pc

### ISSUE THREAD

**Issue by dwlee** [robotics-in-concert/rocon_tools#68]
When I try to connecting concert by qt remocon in remote pc, the role chooser is slowly spawning (about 10s ). So, I follow up this problem and found that `find_service` function is sometimes blockingwhen it executes `service_uri = master.lookupService(service_name)` and `next_service_type = get_service_headers(service_name, service_uri).get('type', None)` in retmote. How we solve this problem?

**Comment by stonier** [comment]
10s worries me...that is way too long for remote communications. There must be some root cause here we don't understand. I would like to find that before making a decision that would be just 'guessing' a fix but maybe not fixing the real problem.

Things to do:

1) put [ros_comm](https://github.com/ros/ros_comm) ([rosmaster is here](https://github.com/ros/ros_comm/tree/indigo-devel/tools/rosmaster)) in your source workspace. Add some debugging in these xmlrpc api callbacks to find out what if rosmaster is getting tired and slow for some reason. Maybe this can help find the root cause.

2) 3 calls here really need only be one call. We don't need to find service three times. If we assume a topic name convention (`get_interactions`, `request_interaction` and `get_roles`) then we only need to find the namespace (i.e. `concert`). 

I didn't want to do this because this breaks if someone remaps the topics. But there is not a reason for anyone to remap these, so I think this is safe. 

Android remocon is already finding the namespace via `findTopic` (see RoconInteractions class in rocon_rosjava_core). This xmlrpc api may be quicker? it also assumes these names are fixed and not remapped. 

3) Worst case....caching, but that can break in alot of ways too. Anyway, caching still needs to look up at least once, so it will still be slow.

**Comment by dwlee** [comment]
This delay phenomenon is only occurred in wireless environment. When `find service` function is called, it continuously calls `lookupService` of [masterapi](https://github.com/ros/ros_comm/blob/indigo-devel/tools/rosgraph/src/rosgraph/masterapi.py#L317-L327) and attempt [connecting socket](https://github.com/ros/ros_comm/blob/indigo-devel/tools/rosservice/src/rosservice/__init__.py#L94-L129) with master in every service registered in master to get service type. In wireless, this processes generally take about 100ms, but sometimes over 3s. If we use this function in wire environments, that is no problem. 

To solve this issue, we need the new api that can obtain information(service name, type, provider, so on)of all services registered in ros master by only one calling, but it is practically difficult, now. Thus, I would keep this issue as todo, try to solve it via `2)` as like as android remocon. Is it ok @stonier ?

**Comment by stonier** [comment]
Good detective work! Now we know exactly that `find_service` is a dangerous style as it is. :neckbeard: 
- Put a LOUD warning in the [find_service](https://github.com/robotics-in-concert/rocon_tools/blob/indigo/rocon_python_comms/src/rocon_python_comms/services.py#L48) comments. Should maybe deprecate this and avoid this style of 'service hunting', but comment will do for now.

For the remocon, exactly as 2) is not perfectly robust. I think we can make it a little better by:
1. Look up the `get_interactions` service, find the namespace (be sure to look for multiple answers) 
2. If you have multiple namespaces, check the type of each <namespace>/get_interactions service
3. `ROS_WARNINGS` if you end up with none or multiple (if none, ask if the user remapped the `get_interactions` service to something else?)
4.  Run as normal, but if `get_roles` or `request_interactions` fails because it can't be found, big warnings again - did these get remapped?

**Comment by stonier** [comment]
Added a big warning to the code here (23f003d2)- other programs should deprecate it and deal with it in various ways (some of which are mentioned above).
