### ISSUE TITLE
[rocon_interactions] support video streamer dynamic binding

### ISSUE THREAD

**Issue by jihoonl** [robotics-in-concert/rocon_tools#81]
Need parameter to configure `web_video_server` parameter to stream out video streaming for webapp.
- `__VIDEO_STREAMER_ADDRESS__`
- `__VIDEO_STREAMER_PORT__`

**Comment by stonier** [comment]
Is this really a responsibility of the interactions manager?

And what happens if you have multiple video streams? You need multiple variables?

**Comment by stonier** [comment]
I am guessing you're including this because you have multiple web app interactions requiring the same parameter and don't want to have this same parameter copy pasted in multiple locations.

We do for rosbridge because that supports an entire category of interactions. This would only support some special use cases and I think the concept breaks if you want to consider serving multiple streams anyway.

I'd rather keep things as minimal as possible rather than have an ever growing list of 'special variables'.

What is possibly a better solution is `parameter reflection`. Any parameter marked with magic characters in the interactions yaml should direct the interactions manager node to look up a parameter on the parameter server and serve that. I am not sure if it's better to just look up parameters in the private namespace, or have those magic character prefixed variables refer to a usual parameter lookup entity. 

e.g. for private lookup, perhaps `__video_streamer_adress__`

e.g. for namespace based `__ROS_PARAM__/video/streamer/address` or `__ROS_PARAM__~video_stream_address`

**Comment by jihoonl** [comment]
:+1: **ROS_PARAM** to give more flexibility sounds good.

**Comment by jihoonl** [comment]
![img_1723](https://cloud.githubusercontent.com/assets/1556736/6958728/f0cb9198-d94a-11e4-973a-87ba8324d147.JPG)

**Comment by jihoonl** [comment]
Reading ros param rule.

`__<PARAM_NAME>__` : read ros param under given interactions namespace.
- namespace is None : reads `rocon_interactions` private param.
- namespace with no leading slash : same namespace as `rocon_interactions` + given namespace
- namespace with leading slash : absolute namespace.

**Comment by jihoonl** [comment]
Param name
- `__PARAM__` : param under namespace
- `__/PARAM__` : param in absolute path
- `__~PARAM__` : **NOT SUPPORTED**
